### ISSUE TITLE
Regarding the datasets

### ISSUE THREAD

**Issue by chaitanya34** [uElectron/Navic-receiver-module-on-rtlsdr#1]
I'm chaitanya kotlapati studying mtech.  im also working on this topic. i have tried to run your code with my datasets i.e i have collected. im not able to findout the preamble and stuck after tracking phase. if its possible will you drop an email regarding how you have collected the data. can you send the datasets that you have processed. my email id- kcjnv22@gmail.com
thanks

**Comment by sk8710** [comment]
cannot import name 'genNavicCaTable' from 'navicCAcodegen

**Comment by uElectron** [comment]
Fixed it in the commit ID : ee4a761
